# Generated by Django 5.1.4 on 2025-01-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityStaff',
            fields=[
                ('staff_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
