# Generated by Django 5.1.4 on 2025-01-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0006_universitystaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
